version: '3.3'

services:
  web:
    build: .
    environment:
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_URI: ${MONGO_URI}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000

  next:
    build: ./nextjs
    ports:
      - "3000:3000"
    # depends_on:
    #   - nginx
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - next
