version: '3.3'

services:

  next:
    build: ./nextjs
    ports:
      - "3000:3000"
  note:
    build: ./note-publish
    ports:
      - "3001:3001"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - next
      - note
